version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - python3-dev
  jobs:
      post_create_environment:
        - pip install .       
        - pip install .[dev]

sphinx:
  configuration: docs/conf.py